// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScriptureCircle.Infrastructure.Data;

#nullable disable

namespace ScriptureCircle.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618030518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HighlightStyle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NoteHtml")
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.Property<string>("NotePlainText")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("ShareSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ShareSlug")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.AnnotationLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnnotationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("AnnotationId");

                    b.ToTable("AnnotationLinks");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.AnnotationTag", b =>
                {
                    b.Property<Guid>("AnnotationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("AnnotationId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("AnnotationTag");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileSlug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfileSlug")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.ContentItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("BookId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VolumeId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("ContentItems");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Notebook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("ShareSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShareSlug")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Notebooks");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.NotebookAnnotation", b =>
                {
                    b.Property<Guid>("NotebookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnnotationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("NotebookId", "AnnotationId");

                    b.HasIndex("AnnotationId");

                    b.ToTable("NotebookAnnotations");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("SubscriberUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriberUserId", "CreatorUserId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Annotation", b =>
                {
                    b.HasOne("ScriptureCircle.Domain.Entities.AppUser", "User")
                        .WithMany("Annotations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ScriptureCircle.Domain.Entities.ScriptureReference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("AnnotationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BookId")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("BookTitle")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)");

                            b1.Property<int>("Chapter")
                                .HasColumnType("integer");

                            b1.Property<int?>("VerseEnd")
                                .HasColumnType("integer");

                            b1.Property<int?>("VerseStart")
                                .HasColumnType("integer");

                            b1.Property<string>("VolumeId")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("AnnotationId");

                            b1.ToTable("Annotations");

                            b1.WithOwner()
                                .HasForeignKey("AnnotationId");
                        });

                    b.OwnsOne("ScriptureCircle.Domain.Entities.ContentAnchor", "ContentAnchor", b1 =>
                        {
                            b1.Property<Guid>("AnnotationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AnchorType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("ContentItemId")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<int?>("EndOffset")
                                .HasColumnType("integer");

                            b1.Property<int?>("EndVerse")
                                .HasColumnType("integer");

                            b1.Property<string>("ParagraphId")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<int?>("StartOffset")
                                .HasColumnType("integer");

                            b1.Property<int?>("StartVerse")
                                .HasColumnType("integer");

                            b1.HasKey("AnnotationId");

                            b1.ToTable("Annotations");

                            b1.WithOwner()
                                .HasForeignKey("AnnotationId");
                        });

                    b.Navigation("ContentAnchor")
                        .IsRequired();

                    b.Navigation("Reference")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.AnnotationLink", b =>
                {
                    b.HasOne("ScriptureCircle.Domain.Entities.Annotation", "Annotation")
                        .WithMany("Links")
                        .HasForeignKey("AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ScriptureCircle.Domain.Entities.ScriptureReference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("AnnotationLinkId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BookId")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("BookTitle")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)");

                            b1.Property<int>("Chapter")
                                .HasColumnType("integer");

                            b1.Property<int?>("VerseEnd")
                                .HasColumnType("integer");

                            b1.Property<int?>("VerseStart")
                                .HasColumnType("integer");

                            b1.Property<string>("VolumeId")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("AnnotationLinkId");

                            b1.ToTable("AnnotationLinks");

                            b1.WithOwner()
                                .HasForeignKey("AnnotationLinkId");
                        });

                    b.Navigation("Annotation");

                    b.Navigation("Reference")
                        .IsRequired();
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.AnnotationTag", b =>
                {
                    b.HasOne("ScriptureCircle.Domain.Entities.Annotation", "Annotation")
                        .WithMany("Tags")
                        .HasForeignKey("AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScriptureCircle.Domain.Entities.Tag", "Tag")
                        .WithMany("Annotations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Annotation");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("ScriptureCircle.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany("Lessons")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ScriptureCircle.Domain.Entities.ScriptureReference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("LessonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BookId")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("BookTitle")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)");

                            b1.Property<int>("Chapter")
                                .HasColumnType("integer");

                            b1.Property<int?>("VerseEnd")
                                .HasColumnType("integer");

                            b1.Property<int?>("VerseStart")
                                .HasColumnType("integer");

                            b1.Property<string>("VolumeId")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("LessonId");

                            b1.ToTable("Lessons");

                            b1.WithOwner()
                                .HasForeignKey("LessonId");
                        });

                    b.Navigation("CreatedByUser");

                    b.Navigation("Reference")
                        .IsRequired();
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Note", b =>
                {
                    b.HasOne("ScriptureCircle.Domain.Entities.AppUser", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ScriptureCircle.Domain.Entities.ScriptureReference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("NoteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BookId")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("BookTitle")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)");

                            b1.Property<int>("Chapter")
                                .HasColumnType("integer");

                            b1.Property<int?>("VerseEnd")
                                .HasColumnType("integer");

                            b1.Property<int?>("VerseStart")
                                .HasColumnType("integer");

                            b1.Property<string>("VolumeId")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("NoteId");

                            b1.ToTable("Notes");

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.Navigation("Reference")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Notebook", b =>
                {
                    b.HasOne("ScriptureCircle.Domain.Entities.AppUser", "User")
                        .WithMany("Notebooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.NotebookAnnotation", b =>
                {
                    b.HasOne("ScriptureCircle.Domain.Entities.Annotation", "Annotation")
                        .WithMany("Notebooks")
                        .HasForeignKey("AnnotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScriptureCircle.Domain.Entities.Notebook", "Notebook")
                        .WithMany("Annotations")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annotation");

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("ScriptureCircle.Domain.Entities.AppUser", "CreatorUser")
                        .WithMany("CreatorSubscriptions")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScriptureCircle.Domain.Entities.AppUser", "SubscriberUser")
                        .WithMany("Following")
                        .HasForeignKey("SubscriberUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("SubscriberUser");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Tag", b =>
                {
                    b.HasOne("ScriptureCircle.Domain.Entities.AppUser", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("ScriptureCircle.Domain.Entities.AppUser", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Annotation", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Notebooks");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("CreatorSubscriptions");

                    b.Navigation("Following");

                    b.Navigation("Lessons");

                    b.Navigation("Notebooks");

                    b.Navigation("Notes");

                    b.Navigation("Subscriptions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Notebook", b =>
                {
                    b.Navigation("Annotations");
                });

            modelBuilder.Entity("ScriptureCircle.Domain.Entities.Tag", b =>
                {
                    b.Navigation("Annotations");
                });
#pragma warning restore 612, 618
        }
    }
}
